import { BlogPost } from "@/lib/types";

export const FALLBACK_BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-1",
    title: "Getting Started with Web Development",
    slug: "getting-started-with-web-development",
    body: "Web development is an exciting field that combines creativity with technical skills. In this comprehensive guide, we'll explore the fundamentals of web development, from HTML and CSS to JavaScript and modern frameworks. Whether you're a complete beginner or looking to refresh your knowledge, this article will provide you with a solid foundation to start your coding journey. We'll cover everything from setting up your development environment to deploying your first website. The world of web development is constantly evolving, with new technologies and frameworks emerging regularly. However, the core principles remain the same, and mastering these fundamentals will serve you well throughout your career. Let's dive into the essential concepts that every web developer should know.",
    excerpt: "Web development is an exciting field that combines creativity with technical skills. In this comprehensive guide, we'll explore the fundamentals...",
    image: "/images/blog/web-development.jpg",
    imageAlt: "Web development workspace with code on screen",
    publishDate: "2024-05-01T10:00:00Z",
    author: {
      id: "author-1",
      name: "Sarah Johnson",
      email: "sarah@codeschool.com",
      avatar: "/images/authors/sarah-johnson.jpg"
    },
    tags: ["Web Development", "HTML", "CSS", "JavaScript", "Tutorial"],
    category: "Tutorial",
    status: "published",
    featured: true,
    viewCount: 1250,
    readTime: 8,
    seoTitle: "Complete Guide to Web Development for Beginners",
    seoDescription: "Learn web development from scratch with our comprehensive guide covering HTML, CSS, JavaScript, and modern frameworks.",
    createdAt: "2024-04-25T10:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z"
  },
  {
    id: "blog-2",
    title: "The Complete Guide to Data Science Career Paths",
    slug: "complete-guide-data-science-career-paths",
    body: "Data science is a rapidly growing field with numerous career opportunities. Whether you're just starting out or looking to transition into data science, understanding the different career paths available is crucial for making informed decisions about your professional development. In this comprehensive guide, we'll explore various roles in data science, from data analyst to machine learning engineer, and provide insights into the skills, responsibilities, and growth opportunities associated with each path. We'll also discuss the educational requirements, certifications, and practical experience needed to succeed in each role. By the end of this article, you'll have a clear understanding of which data science career path aligns best with your interests, skills, and career goals.",
    excerpt: "Data science is a rapidly growing field with numerous career opportunities. Whether you're just starting out or looking to transition...",
    image: "/images/blog/data-science-careers.jpg",
    imageAlt: "Data science career paths visualization",
    publishDate: "2024-05-08T10:00:00Z",
    author: {
      id: "author-2",
      name: "Dr. Emily Rodriguez",
      email: "emily@codeschool.com",
      avatar: "/images/authors/emily-rodriguez.jpg"
    },
    tags: ["Data Science", "Career", "Machine Learning", "Analytics"],
    category: "Career",
    status: "published",
    featured: false,
    viewCount: 892,
    readTime: 12,
    seoTitle: "Data Science Career Paths: Complete Guide for 2024",
    seoDescription: "Explore different career paths in data science, from data analyst to machine learning engineer, and learn how to choose the right path for you.",
    createdAt: "2024-05-06T10:00:00Z",
    updatedAt: "2024-05-08T10:00:00Z"
  },
  {
    id: "blog-3",
    title: "UI/UX Design Trends for 2024",
    slug: "ui-ux-design-trends-2024",
    body: "As we move through 2024, several design trends are emerging that will influence how we create digital experiences. From minimalist interfaces to bold typography, these trends reflect the evolving needs of users and the capabilities of modern technology. In this article, we'll explore the most significant UI/UX design trends that are shaping the digital landscape this year. We'll examine how these trends impact user experience, accessibility, and overall design philosophy. Whether you're a seasoned designer or just starting out, understanding these trends will help you create more engaging and effective digital products. Let's dive into the design trends that are defining 2024 and beyond.",
    excerpt: "As we move through 2024, several design trends are emerging that will influence how we create digital experiences...",
    image: "/images/blog/ui-ux-trends.jpg",
    imageAlt: "UI/UX design trends showcase",
    publishDate: "2024-05-05T10:00:00Z",
    author: {
      id: "author-3",
      name: "Alex Thompson",
      email: "alex@codeschool.com",
      avatar: "/images/authors/alex-thompson.jpg"
    },
    tags: ["UI Design", "UX Design", "Trends", "Design"],
    category: "Design",
    status: "published",
    featured: true,
    viewCount: 1156,
    readTime: 10,
    seoTitle: "UI/UX Design Trends 2024: What's New in Digital Design",
    seoDescription: "Stay ahead of the curve with these emerging UI/UX design trends that will shape digital experiences in 2024 and beyond.",
    createdAt: "2024-05-03T10:00:00Z",
    updatedAt: "2024-05-05T10:00:00Z"
  },
  {
    id: "blog-4",
    title: "DevOps Best Practices for Modern Applications",
    slug: "devops-best-practices-modern-applications",
    body: "DevOps has become an essential practice for modern software development, enabling teams to deliver high-quality software faster and more reliably. In this comprehensive guide, we'll explore the key DevOps practices that every development team should implement to improve their software delivery pipeline. From continuous integration and continuous deployment (CI/CD) to infrastructure as code and monitoring, we'll cover the essential practices that form the foundation of a successful DevOps culture. We'll also discuss the tools and technologies that support these practices, helping you build a robust and efficient development workflow. Whether you're new to DevOps or looking to optimize your existing processes, this guide will provide you with actionable insights to improve your software delivery capabilities.",
    excerpt: "DevOps has become an essential practice for modern software development, enabling teams to deliver high-quality software faster...",
    image: "/images/blog/devops-practices.jpg",
    imageAlt: "DevOps workflow diagram",
    publishDate: "2024-05-03T10:00:00Z",
    author: {
      id: "author-4",
      name: "David Kim",
      email: "david@codeschool.com",
      avatar: "/images/authors/david-kim.jpg"
    },
    tags: ["DevOps", "CI/CD", "Docker", "Kubernetes"],
    category: "DevOps",
    status: "published",
    featured: false,
    viewCount: 634,
    readTime: 15,
    seoTitle: "DevOps Best Practices: Complete Guide for 2024",
    seoDescription: "Learn essential DevOps practices that will help you build, deploy, and maintain modern applications more effectively.",
    createdAt: "2024-05-01T10:00:00Z",
    updatedAt: "2024-05-03T10:00:00Z"
  },
  {
    id: "blog-5",
    title: "Building Cross-Platform Mobile Apps with React Native",
    slug: "building-cross-platform-mobile-apps-react-native",
    body: "React Native has revolutionized mobile app development by allowing developers to write once and run everywhere. This powerful framework enables you to build native-feeling mobile applications for both iOS and Android using a single codebase. In this detailed guide, we'll explore the fundamentals of React Native development, from setting up your development environment to deploying your app to app stores. We'll cover essential concepts like components, navigation, state management, and platform-specific code. We'll also discuss best practices for performance optimization, testing, and maintaining your React Native applications. Whether you're a web developer looking to expand into mobile or a mobile developer seeking a more efficient development process, this guide will help you master React Native development.",
    excerpt: "React Native has revolutionized mobile app development by allowing developers to write once and run everywhere...",
    image: "/images/blog/react-native-mobile.jpg",
    imageAlt: "React Native mobile app development",
    publishDate: "2024-05-01T10:00:00Z",
    author: {
      id: "author-5",
      name: "Lisa Wang",
      email: "lisa@codeschool.com",
      avatar: "/images/authors/lisa-wang.jpg"
    },
    tags: ["React Native", "Mobile Development", "iOS", "Android"],
    category: "Mobile Development",
    status: "published",
    featured: false,
    viewCount: 756,
    readTime: 18,
    seoTitle: "React Native Mobile Development: Complete Guide 2024",
    seoDescription: "Discover how to build efficient, native-feeling mobile applications for both iOS and Android using React Native.",
    createdAt: "2024-04-29T10:00:00Z",
    updatedAt: "2024-05-01T10:00:00Z"
  },
  {
    id: "blog-6",
    title: "The Future of Web Development: What to Expect",
    slug: "future-web-development-what-to-expect",
    body: "Web development is constantly evolving, and staying ahead of the curve is crucial for developers who want to remain relevant in this fast-paced industry. In this forward-looking article, we'll explore the emerging technologies and trends that are shaping the future of web development. From artificial intelligence and machine learning integration to progressive web apps and edge computing, we'll examine the technologies that will define the next generation of web applications. We'll also discuss the skills and knowledge that developers should focus on to prepare for these changes. Whether you're a seasoned developer or just starting your journey, understanding these future trends will help you make informed decisions about your career development and technology choices.",
    excerpt: "Web development is constantly evolving, and staying ahead of the curve is crucial for developers who want to remain relevant...",
    image: "/images/blog/future-web-dev.jpg",
    imageAlt: "Future of web development concept",
    publishDate: "2024-04-28T10:00:00Z",
    author: {
      id: "author-6",
      name: "Michael Chen",
      email: "michael@codeschool.com",
      avatar: "/images/authors/michael-chen.jpg"
    },
    tags: ["Web Development", "Future", "Technology", "Trends"],
    category: "Technology",
    status: "published",
    featured: true,
    viewCount: 923,
    readTime: 14,
    seoTitle: "Future of Web Development: Trends and Technologies 2024",
    seoDescription: "Explore emerging technologies and trends that will shape the future of web development in the coming years.",
    createdAt: "2024-04-26T10:00:00Z",
    updatedAt: "2024-04-28T10:00:00Z"
  },
  {
    id: "blog-7",
    title: "Getting Started with Machine Learning: A Beginner's Guide",
    slug: "getting-started-machine-learning-beginners-guide",
    body: "Machine learning can seem intimidating at first, but with the right approach and resources, anyone can get started on this exciting journey. In this comprehensive beginner's guide, we'll demystify machine learning and provide you with a clear roadmap to begin your ML journey. We'll start with the fundamental concepts and gradually build up to more advanced topics. You'll learn about different types of machine learning, essential algorithms, and the tools and frameworks that make ML accessible to beginners. We'll also provide practical examples and hands-on exercises to help you apply what you learn. By the end of this guide, you'll have a solid foundation in machine learning and the confidence to tackle more advanced topics and projects.",
    excerpt: "Machine learning can seem intimidating at first, but with the right approach and resources, anyone can get started...",
    image: "/images/blog/ml-beginners-guide.jpg",
    imageAlt: "Machine learning beginner's guide illustration",
    publishDate: "2024-04-25T10:00:00Z",
    author: {
      id: "author-2",
      name: "Dr. Emily Rodriguez",
      email: "emily@codeschool.com",
      avatar: "/images/authors/emily-rodriguez.jpg"
    },
    tags: ["Machine Learning", "AI", "Python", "Beginners"],
    category: "Data Science",
    status: "published",
    featured: false,
    viewCount: 1456,
    readTime: 20,
    seoTitle: "Machine Learning for Beginners: Complete Guide 2024",
    seoDescription: "Start your machine learning journey with this comprehensive guide covering the basics, tools, and resources you need to know.",
    createdAt: "2024-04-23T10:00:00Z",
    updatedAt: "2024-04-25T10:00:00Z"
  },
  {
    id: "blog-8",
    title: "How to Build a Successful Tech Career: Tips from Industry Experts",
    slug: "build-successful-tech-career-tips-industry-experts",
    body: "Building a successful career in tech requires more than just technical skills. In this insightful article, we've gathered advice from successful tech professionals across various roles and industries to help you navigate your career path. We'll explore the essential soft skills, networking strategies, and mindset shifts that contribute to long-term success in the technology sector. From junior developers to senior executives, our experts share their experiences and lessons learned throughout their careers. You'll learn about the importance of continuous learning, building meaningful relationships, and developing a growth mindset. We'll also discuss common career pitfalls and how to avoid them, as well as strategies for advancing your career in different tech roles.",
    excerpt: "Building a successful career in tech requires more than just technical skills. Here's what industry experts have to say...",
    image: "/images/blog/tech-career-tips.jpg",
    imageAlt: "Tech career success tips",
    publishDate: "2024-04-22T10:00:00Z",
    author: {
      id: "author-7",
      name: "Maria Garcia",
      email: "maria@codeschool.com",
      avatar: "/images/authors/maria-garcia.jpg"
    },
    tags: ["Career", "Tech", "Professional Development", "Success"],
    category: "Career",
    status: "published",
    featured: false,
    viewCount: 1087,
    readTime: 16,
    seoTitle: "Tech Career Success: Expert Tips and Strategies 2024",
    seoDescription: "Learn from successful tech professionals about the strategies and mindset needed to build a thriving career in technology.",
    createdAt: "2024-04-20T10:00:00Z",
    updatedAt: "2024-04-22T10:00:00Z"
  }
];