import { Course } from "@/lib/types";

export const FALLBACK_COURSES: Course[] = [
  {
    id: "course-1",
    title: "Complete Web Development Bootcamp",
    description: "Master modern web development with HTML, CSS, JavaScript, React, Node.js, and MongoDB. Build real-world projects and get job-ready skills.",
    shortDescription: "Master modern web development with HTML, CSS, JavaScript, React, Node.js, and MongoDB.",
    instructor: "Sarah Johnson",
    duration: "12 weeks",
    level: "beginner",
    price: 299,
    originalPrice: 599,
    image: "/images/courses/web-dev-bootcamp.jpg",
    category: "Web Development",
    tags: ["HTML", "CSS", "JavaScript", "React", "Node.js", "MongoDB"],
    isActive: true,
    enrollmentCount: 1247,
    rating: 4.8,
    reviewCount: 342,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  },
  {
    id: "course-2",
    title: "Advanced React Patterns",
    description: "Deep dive into advanced React concepts including hooks, context, performance optimization, and testing strategies.",
    shortDescription: "Deep dive into advanced React concepts including hooks, context, and performance optimization.",
    instructor: "Michael Chen",
    duration: "8 weeks",
    level: "intermediate",
    price: 199,
    image: "/images/courses/advanced-react.jpg",
    category: "Frontend Development",
    tags: ["React", "Hooks", "Context", "Performance", "Testing"],
    isActive: true,
    enrollmentCount: 892,
    rating: 4.9,
    reviewCount: 156,
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  },
  {
    id: "course-3",
    title: "Data Science with Python",
    description: "Learn data analysis, machine learning, and visualization using Python, Pandas, NumPy, and Scikit-learn.",
    shortDescription: "Learn data analysis, machine learning, and visualization using Python and popular libraries.",
    instructor: "Dr. Emily Rodriguez",
    duration: "16 weeks",
    level: "intermediate",
    price: 399,
    originalPrice: 799,
    image: "/images/courses/data-science-python.jpg",
    category: "Data Science",
    tags: ["Python", "Pandas", "NumPy", "Scikit-learn", "Machine Learning"],
    isActive: true,
    enrollmentCount: 634,
    rating: 4.7,
    reviewCount: 98,
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  },
  {
    id: "course-4",
    title: "UI/UX Design Fundamentals",
    description: "Master the principles of user interface and user experience design. Learn Figma, prototyping, and design thinking.",
    shortDescription: "Master the principles of user interface and user experience design with Figma and prototyping.",
    instructor: "Alex Thompson",
    duration: "10 weeks",
    level: "beginner",
    price: 249,
    image: "/images/courses/ui-ux-design.jpg",
    category: "Design",
    tags: ["UI Design", "UX Design", "Figma", "Prototyping", "Design Thinking"],
    isActive: true,
    enrollmentCount: 1156,
    rating: 4.6,
    reviewCount: 203,
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  },
  {
    id: "course-5",
    title: "DevOps and Cloud Computing",
    description: "Learn Docker, Kubernetes, AWS, and CI/CD pipelines. Master modern DevOps practices and cloud deployment.",
    shortDescription: "Learn Docker, Kubernetes, AWS, and CI/CD pipelines for modern DevOps practices.",
    instructor: "David Kim",
    duration: "14 weeks",
    level: "advanced",
    price: 449,
    originalPrice: 899,
    image: "/images/courses/devops-cloud.jpg",
    category: "DevOps",
    tags: ["Docker", "Kubernetes", "AWS", "CI/CD", "Cloud Computing"],
    isActive: true,
    enrollmentCount: 423,
    rating: 4.8,
    reviewCount: 67,
    createdAt: "2024-01-25T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  },
  {
    id: "course-6",
    title: "Mobile App Development with React Native",
    description: "Build cross-platform mobile apps using React Native. Learn navigation, state management, and app store deployment.",
    shortDescription: "Build cross-platform mobile apps using React Native with navigation and state management.",
    instructor: "Lisa Wang",
    duration: "12 weeks",
    level: "intermediate",
    price: 329,
    image: "/images/courses/react-native.jpg",
    category: "Mobile Development",
    tags: ["React Native", "Mobile Development", "iOS", "Android", "Navigation"],
    isActive: true,
    enrollmentCount: 567,
    rating: 4.5,
    reviewCount: 89,
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  }
];
