import { Event } from "@/lib/types";

export const FALLBACK_EVENTS: Event[] = [
  {
    id: "event-1",
    title: "Web Development Workshop",
    description: "Hands-on workshop covering modern web development techniques, React best practices, and deployment strategies.",
    date: "2024-06-15",
    time: "10:00 AM - 4:00 PM",
    location: "Tech Hub, Downtown",
    type: "workshop",
    price: 99,
    maxAttendees: 50,
    currentAttendees: 32,
    image: "/images/events/web-dev-workshop.jpg",
    isActive: true,
    createdAt: "2024-05-01T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  },
  {
    id: "event-2",
    title: "Data Science Conference 2024",
    description: "Annual conference featuring industry leaders discussing the latest trends in data science, AI, and machine learning.",
    date: "2024-07-20",
    time: "9:00 AM - 6:00 PM",
    location: "Convention Center",
    type: "conference",
    price: 299,
    maxAttendees: 500,
    currentAttendees: 287,
    image: "/images/events/data-science-conference.jpg",
    isActive: true,
    createdAt: "2024-04-15T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  },
  {
    id: "event-3",
    title: "UI/UX Design Meetup",
    description: "Monthly meetup for designers to share experiences, discuss trends, and network with fellow professionals.",
    date: "2024-06-08",
    time: "6:00 PM - 8:00 PM",
    location: "Design Studio, Creative District",
    type: "meetup",
    price: 0,
    maxAttendees: 30,
    currentAttendees: 18,
    image: "/images/events/ui-ux-meetup.jpg",
    isActive: true,
    createdAt: "2024-05-10T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  },
  {
    id: "event-4",
    title: "DevOps Best Practices Seminar",
    description: "Learn about modern DevOps practices, containerization, and cloud deployment strategies from industry experts.",
    date: "2024-08-12",
    time: "2:00 PM - 5:00 PM",
    location: "Cloud Solutions Inc.",
    type: "seminar",
    price: 149,
    maxAttendees: 100,
    currentAttendees: 45,
    image: "/images/events/devops-seminar.jpg",
    isActive: true,
    createdAt: "2024-05-05T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  },
  {
    id: "event-5",
    title: "Mobile App Development Bootcamp",
    description: "Intensive 3-day bootcamp covering React Native, Flutter, and native mobile development approaches.",
    date: "2024-09-15",
    time: "9:00 AM - 5:00 PM",
    location: "Mobile Innovation Lab",
    type: "workshop",
    price: 399,
    maxAttendees: 25,
    currentAttendees: 12,
    image: "/images/events/mobile-bootcamp.jpg",
    isActive: true,
    createdAt: "2024-05-12T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  },
  {
    id: "event-6",
    title: "Tech Career Fair 2024",
    description: "Connect with top tech companies, startups, and recruiters. Perfect for job seekers and career changers.",
    date: "2024-10-05",
    time: "10:00 AM - 4:00 PM",
    location: "Exhibition Hall",
    type: "conference",
    price: 0,
    maxAttendees: 1000,
    currentAttendees: 456,
    image: "/images/events/tech-career-fair.jpg",
    isActive: true,
    createdAt: "2024-04-20T10:00:00Z",
    updatedAt: "2024-05-14T10:00:00Z"
  }
];
