// services/marketingAutomation.js
import mongoose from "mongoose";
import { StudentEvaluation, MarketingAction, MarketingCampaign } from "@/lib/models";
import Student from "../models/Student";
import Group from "../models/Group";
import Course from "../models/Course";

/**
 * ✅ EVENT: Instructor Evaluation Submitted
 */
export async function triggerEvaluationFollowup(evaluationId, triggeredBy) {
  try {
    console.log(`\n🎯 EVENT: Instructor Evaluation Submitted ==========`);
    console.log(`📝 Evaluation: ${evaluationId}`);
    console.log(`👤 Triggered by: ${triggeredBy}`);

    // جلب التقييم مع البيانات المرتبطة
    const evaluation = await StudentEvaluation.findById(evaluationId)
      .populate(
        "studentId",
        "personalInfo.fullName personalInfo.whatsappNumber personalInfo.email communicationPreferences"
      )
      .populate("groupId", "name code courseId")
      .populate({
        path: "groupId",
        populate: {
          path: "courseId",
          select: "title level",
        },
      });

    if (!evaluation || !evaluation.studentId || !evaluation.groupId) {
      throw new Error("Evaluation data incomplete");
    }

    const student = evaluation.studentId;
    const group = evaluation.groupId;
    const course = group.courseId;

    console.log(`📊 Evaluation details:`);
    console.log(`   Student: ${student.personalInfo?.fullName}`);
    console.log(`   Group: ${group.name} (${group.code})`);
    console.log(`   Course: ${course?.title}`);
    console.log(`   Decision: ${evaluation.finalDecision}`);
    console.log(`   Overall Score: ${evaluation.calculatedStats?.overallScore}`);

    // التحقق من وجود حملة تسويقية نشطة
    let campaign = await MarketingCampaign.findOne({
      campaignType: "evaluation_followup",
      status: "active",
      "targetCriteria.evaluationDecisions": evaluation.finalDecision,
    });

    // إذا لم توجد حملة، إنشاء حملة تلقائية
    if (!campaign) {
      campaign = await createAutoCampaign(evaluation.finalDecision, triggeredBy);
    }

    // إنشاء إجراء تسويقي
    const marketingAction = await MarketingAction.create({
      actionType: getActionType(evaluation.finalDecision),
      targetStudent: evaluation.studentId._id,
      targetGroup: evaluation.groupId._id,
      evaluationId: evaluation._id,
      actionData: await generateActionData(evaluation, student, group, course),
      communicationChannels: {
        whatsapp: true,
        email: student.personalInfo?.email ? true : false,
        sms: false,
      },
      status: "pending",
      metadata: {
        createdBy: triggeredBy,
        createdAt: new Date(),
      },
    });

    console.log(`✅ Marketing action created: ${marketingAction._id}`);

    // تنفيذ الإجراء التسويقي
    await executeMarketingAction(marketingAction._id);

    // تحديث التقييم
    await StudentEvaluation.findByIdAndUpdate(evaluationId, {
      $push: { "marketing.followupActions": marketingAction._id },
      $set: {
        "marketing.followupCampaign": campaign._id,
        "marketing.followupStatus": "completed",
        "metadata.updatedAt": new Date(),
      },
    });

    return {
      success: true,
      actionId: marketingAction._id,
      campaignId: campaign._id,
      studentCategory: evaluation.marketing?.studentCategory,
      nextSteps: evaluation.marketing?.nextSteps,
    };
  } catch (error) {
    console.error("❌ Error in triggerEvaluationFollowup:", error);
    throw error;
  }
}

/**
 * ✅ إنشاء حملة تسويقية تلقائية
 */
async function createAutoCampaign(decision, createdBy) {
  console.log(`📝 Creating auto campaign for decision: ${decision}`);

  const campaignData = {
    name: `Auto Campaign - ${decision.toUpperCase()}`,
    description: `Automatically generated campaign for ${decision} evaluation decisions`,
    campaignType: "evaluation_followup",
    targetCriteria: {
      evaluationDecisions: [decision],
    },
    automationRules: {
      trigger: "evaluation_completed",
      delayHours: 24,
      maxRetries: 3,
      followupSchedule: [
        { daysAfter: 3, actionType: "followup" },
        { daysAfter: 7, actionType: "reminder" },
      ],
    },
    messages: generateMessageTemplates(decision),
    offers: generateOffers(decision),
    status: "active",
    metadata: {
      createdBy,
      createdAt: new Date(),
      autoGenerated: true,
    },
  };

  const campaign = await MarketingCampaign.create(campaignData);
  console.log(`✅ Auto campaign created: ${campaign._id}`);
  return campaign;
}

/**
 * ✅ تحديد نوع الإجراء بناءً على القرار
 */
function getActionType(decision) {
  const actionMap = {
    pass: "upsell",
    review: "support",
    repeat: "re_enroll",
  };
  return actionMap[decision] || "support";
}

/**
 * ✅ توليد بيانات الإجراء التسويقي
 */
async function generateActionData(evaluation, student, group, course) {
  console.log("🧠 Generating AI-powered action data...");

  const weakPoints = evaluation.weakPoints || [];
  const strengths = evaluation.strengths || [];

  // توليد رسالة ذكية
  const aiMessage = generateAIMessage(evaluation, student, group, course);

  // تحديد العرض المناسب
  const offer = generateOffer(
    evaluation.finalDecision,
    evaluation.calculatedStats?.overallScore
  );

  return {
    customMessage: aiMessage,
    discountPercentage: offer.discount,
    supportPackage: offer.support,
    nextLevel: offer.nextLevel,
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    weakPoints,
    aiGenerated: true,
    generatedAt: new Date(),
  };
}

/**
 * ✅ توليد رسالة ذكية
 */
function generateAIMessage(evaluation, student, group, course) {
  const studentName = student.personalInfo?.fullName || "طالبنا العزيز";
  const courseName = course?.title || "الكورس";

  // نقاط القوة والضعف
  const weakPointsAr = evaluation.weakPoints?.map((wp) => {
    const map = {
      understanding: "الفهم النظري",
      practice: "الممارسة العملية",
      attendance: "الانتظام في الحضور",
      participation: "المشاركة في الفصل",
      homework: "إنجاز الواجبات",
      projects: "تنفيذ المشاريع",
    };
    return map[wp] || wp;
  }) || [];

  const strengthsAr = evaluation.strengths?.map((st) => {
    const map = {
      fast_learner: "سرعة التعلم",
      hard_worker: "الاجتهاد",
      team_player: "العمل الجماعي",
      creative: "الإبداع",
      problem_solver: "حل المشكلات",
      consistent: "الانتظام",
    };
    return map[st] || st;
  }) || [];

  switch (evaluation.finalDecision) {
    case "pass":
      if (evaluation.calculatedStats?.overallScore >= 4.5) {
        return `🎉 مبروك ${studentName}!
أداؤك في ${courseName} كان استثنائياً! 🏆
${strengthsAr.length > 0 ? `نقاط قوتك: ${strengthsAr.join(" و ")} 👏` : ""}
مستعد للتحدي القادم؟ عندنا الكورس المتقدم بخصم 20% خاص لك.
أنت أيضاً مؤهل لبرنامج الإحالات - كل صديق تجيبه ليك 15% خصم إضافي!

⏰ العرض ساري لمدة أسبوع فقط!
🚀 انطلق للمستوى التالي!`;
      } else {
        return `👍 أحسنت ${studentName}!
أكملت ${courseName} بنجاح 🎓
${weakPointsAr.length > 0 ? `نصيحة: ركز أكثر على ${weakPointsAr[0]} في المستوى القادم 💡` : ""}
مستعد للمستوى التالي؟ عندك خصم 15% على التسجيل المبكر.

📞 تواصل معنا خلال أسبوع للحصول على الخصم!`;
      }

    case "review":
      if (weakPointsAr.length > 2) {
        return `🔔 ${studentName}، عندنا خطة خاصة لك!
نعرف إن ${courseName} كان تحدياً 💪
${weakPointsAr.length > 0 ? `المناطق اللي محتاجة دعم: ${weakPointsAr.join("، ")}` : ""}

بنقترح:
✅ جلسات دعم مكثفة (3 جلسات مجانية)
✅ مراجعة جميع المشاريع مع مدرب متخصص
✅ خصم 30% للاستمرار معنا في المستوى الحالي

🎯 هدفنا: نوصل معاك لـ 100% استفادة!
📞 رد علينا عشان نبدأ الخطة!`;
      } else {
        return `👋 ${studentName}، أداؤك جيد في ${courseName}!
لكن محتاج تدعيم بسيط في: ${weakPointsAr.join(" و ")}

عندنا جلسات دعم مجانية الأسبوع الجاي:
📅 الأحد، الإثنين، الأربعاء
⏰ من 6-8 مساءً
🎯 تركيز على ${weakPointsAr[0] || "المهارات العملية"}

🆓 مجاناً تماماً!`;
      }

    case "repeat":
      return `🔄 ${studentName}، علشان تستفيد 100%
بنقترح إعادة ${courseName} مع:
✅ دعم إضافي شخصي (جلسة أسبوعياً)
✅ خصم 40% على إعادة الكورس
✅ مراجعة جميع المشاريع والدروس
✅ متابعة أسبوعية مع المدرب

${weakPointsAr.length > 0 ? `هنركز معاك على: ${weakPointsAr.join(" و ")} 🎯` : ""}

💪 المستوى الجاي بتكون أقوى ومستعد 100%!
💰 السعر بعد الخصم: [السعر الأصلي × 60%]
📞 رد علشان نحجز مكانك!`;

    default:
      return `مرحباً ${studentName}،
تهانينا على إتمام ${courseName}!
نتمنى لك التوفيق في مسيرتك التعليمية.`;
  }
}

/**
 * ✅ توليد العروض بناءً على القرار والنتيجة
 */
function generateOffer(decision, overallScore) {
  const offers = {
    pass: {
      discount: overallScore >= 4.5 ? 20 : 15,
      support: "advanced_level_access",
      nextLevel: "المستوى المتقدم",
    },
    review: {
      discount: 30,
      support: "intensive_support_package",
      nextLevel: "نفس المستوى مع دعم",
    },
    repeat: {
      discount: 40,
      support: "personal_coaching",
      nextLevel: "إعادة الكورس",
    },
  };

  return offers[decision] || {
    discount: 10,
    support: "basic_support",
    nextLevel: "المستوى التالي",
  };
}

/**
 * ✅ توليد قوالب الرسائل
 */
function generateMessageTemplates(decision) {
  const templates = {
    pass: {
      template: `مبروك {studentName}! 🎉
أداؤك في {courseName} كان {performance}.
مستعد للمستوى التالي? عندك خصم {discount}%!
{strengthsMessage}
{offerMessage}`,
      variables: [
        "studentName",
        "courseName",
        "performance",
        "discount",
        "strengthsMessage",
        "offerMessage",
      ],
      aiEnhanced: true,
    },
    review: {
      template: `{studentName}، أداؤك في {courseName} جيد 👋
لكن محتاج تدعيم في: {weakPoints}
عندنا {supportPackage} بخصم {discount}%!
{nextSteps}`,
      variables: [
        "studentName",
        "courseName",
        "weakPoints",
        "supportPackage",
        "discount",
        "nextSteps",
      ],
      aiEnhanced: true,
    },
    repeat: {
      template: `{studentName}، علشان تستفيد 100% 🎯
بنقترح إعادة {courseName} مع:
✅ {supportPackage}
✅ خصم {discount}%
✅ {additionalBenefits}
مستعد للانطلاق من جديد? 💪`,
      variables: [
        "studentName",
        "courseName",
        "supportPackage",
        "discount",
        "additionalBenefits",
      ],
      aiEnhanced: true,
    },
  };

  return templates[decision] || templates.review;
}

/**
 * ✅ توليد العروض العامة
 */
function generateOffers(decision) {
  const offers = {
    pass: {
      discountPercentage: 15,
      supportSessions: 0,
      deadlineDays: 7,
      referralBonus: "خصم 15% إضافي لكل صديق",
    },
    review: {
      discountPercentage: 30,
      supportSessions: 3,
      deadlineDays: 14,
      referralBonus: "جلسة دعم مجانية",
    },
    repeat: {
      discountPercentage: 40,
      supportSessions: 8,
      deadlineDays: 30,
      referralBonus: "خصم 20% على كورس آخر",
    },
  };

  return offers[decision] || offers.review;
}

/**
 * ✅ تنفيذ الإجراء التسويقي
 */
async function executeMarketingAction(actionId) {
  try {
    console.log(`🚀 Executing marketing action: ${actionId}`);

    const action = await MarketingAction.findById(actionId)
      .populate(
        "targetStudent",
        "personalInfo.fullName personalInfo.whatsappNumber personalInfo.email"
      )
      .populate("targetGroup", "name code");

    if (!action) {
      throw new Error("Marketing action not found");
    }

    const student = action.targetStudent;
    const whatsappNumber = student.personalInfo?.whatsappNumber;

    if (!whatsappNumber) {
      console.log(`⚠️ No WhatsApp number for student ${student.personalInfo?.fullName}`);
      action.status = "failed";
      action.results.notes = "No WhatsApp number";
      await action.save();
      return;
    }

    // محاكاة إرسال الرسالة (يجب استبدالها بـ wapilotService الحقيقي)
    console.log(`📤 Simulating WhatsApp message to ${whatsappNumber}:`);
    console.log(`Message: ${action.actionData.customMessage.substring(0, 100)}...`);

    // محاكاة نجاح الإرسال
    action.status = "completed";
    action.results.messageSent = true;
    action.results.sentAt = new Date();
    action.metadata.executedAt = new Date();
    action.metadata.executionLogs.push(
      `Message simulated successfully at ${new Date().toISOString()}`
    );

    console.log(`✅ Marketing message simulated to ${student.personalInfo?.fullName}`);

    await action.save();

    // تحديث إحصائيات الحملة إذا كانت مرتبطة
    if (action.evaluationId) {
      await updateCampaignStats(action.evaluationId.marketing?.followupCampaign);
    }
  } catch (error) {
    console.error(`❌ Error executing marketing action ${actionId}:`, error);

    await MarketingAction.findByIdAndUpdate(actionId, {
      $set: {
        status: "failed",
        "results.notes": error.message,
        "metadata.executionLogs": [`Error: ${error.message}`],
      },
    });
  }
}

/**
 * ✅ تحديث إحصائيات الحملة
 */
async function updateCampaignStats(campaignId) {
  try {
    if (!campaignId) return;

    const stats = await MarketingAction.aggregate([
      {
        $match: {
          $or: [
            { "metadata.campaignId": campaignId },
            { "evaluationId.marketing.followupCampaign": campaignId }
          ]
        }
      },
      {
        $group: {
          _id: "$status",
          count: { $sum: 1 },
        },
      },
    ]);

    const total = stats.reduce((sum, stat) => sum + stat.count, 0);
    const completed = stats.find((s) => s._id === "completed")?.count || 0;
    const conversionRate = total > 0 ? (completed / total) * 100 : 0;

    await MarketingCampaign.findByIdAndUpdate(campaignId, {
      $set: {
        "stats.totalTargets": total,
        "stats.messagesSent": completed,
        "stats.conversions": completed,
        "stats.conversionRate": parseFloat(conversionRate.toFixed(2)),
      },
    });
  } catch (error) {
    console.error("❌ Error updating campaign stats:", error);
  }
}

/**
 * ✅ EVENT: Group Completed - Marketing Followup
 */
export async function onGroupCompletedMarketing(groupId, triggeredBy) {
  try {
    console.log(`\n🎯 EVENT: Group Completed - Marketing Followup ==========`);
    console.log(`👥 Group: ${groupId}`);

    const evaluations = await StudentEvaluation.find({
      groupId,
      isDeleted: false,
      "marketing.followupStatus": { $ne: "completed" },
    })
      .populate("studentId", "personalInfo.fullName personalInfo.whatsappNumber")
      .lean();

    console.log(`📊 Found ${evaluations.length} evaluations for marketing followup`);

    if (evaluations.length === 0) {
      console.log("⚠️ No evaluations found for marketing followup");
      return {
        success: false,
        message: "No evaluations found for marketing followup",
      };
    }

    const campaign = await MarketingCampaign.create({
      name: `Group Completion - ${groupId}`,
      description: `Marketing followup for completed group ${groupId}`,
      campaignType: "group_completed",
      targetCriteria: { groups: [groupId] },
      automationRules: {
        trigger: "group_completed",
        delayHours: 48,
        maxRetries: 2,
      },
      status: "active",
      metadata: {
        createdBy: triggeredBy,
        createdAt: new Date(),
      },
    });

    let successCount = 0;
    let failCount = 0;
    const results = [];

    for (const evaluation of evaluations) {
      try {
        const result = await triggerEvaluationFollowup(evaluation._id, triggeredBy);
        if (result.success) {
          successCount++;
          results.push({
            studentId: evaluation.studentId._id,
            studentName: evaluation.studentId.personalInfo?.fullName,
            success: true,
            actionId: result.actionId,
          });
        } else {
          failCount++;
          results.push({
            studentId: evaluation.studentId._id,
            studentName: evaluation.studentId.personalInfo?.fullName,
            success: false,
            error: result.error,
          });
        }
      } catch (error) {
        failCount++;
        results.push({
          studentId: evaluation.studentId._id,
          studentName: evaluation.studentId.personalInfo?.fullName,
          success: false,
          error: error.message,
        });
      }
    }

    console.log(`\n📊 Group completion marketing results:`);
    console.log(`   Success: ${successCount}`);
    console.log(`   Failed: ${failCount}`);
    console.log(`   Campaign: ${campaign._id}`);

    await MarketingCampaign.findByIdAndUpdate(campaign._id, {
      $set: {
        "stats.totalTargets": evaluations.length,
        "stats.messagesSent": successCount,
        "stats.conversions": 0,
        "stats.conversionRate": parseFloat(((successCount / evaluations.length) * 100).toFixed(2)),
        "stats.startDate": new Date(),
      },
    });

    return {
      success: successCount > 0,
      campaignId: campaign._id,
      total: evaluations.length,
      successCount,
      failCount,
      results,
    };
  } catch (error) {
    console.error("❌ Error in onGroupCompletedMarketing:", error);
    throw error;
  }
}

/**
 * ✅ الحصول على إحصائيات التسويق
 */
export async function getMarketingStats(timeframe = "month") {
  try {
    const dateFilter = getDateFilter(timeframe);

    const stats = await MarketingAction.aggregate([
      {
        $match: {
          createdAt: dateFilter,
        },
      },
      {
        $group: {
          _id: "$actionType",
          total: { $sum: 1 },
          completed: { $sum: { $cond: [{ $eq: ["$status", "completed"] }, 1, 0] } },
          failed: { $sum: { $cond: [{ $eq: ["$status", "failed"] }, 1, 0] } },
        },
      },
    ]);

    const totalStats = await MarketingAction.aggregate([
      {
        $match: {
          createdAt: dateFilter,
        },
      },
      {
        $group: {
          _id: null,
          totalActions: { $sum: 1 },
          totalCompleted: { $sum: { $cond: [{ $eq: ["$status", "completed"] }, 1, 0] } },
          uniqueStudents: { $addToSet: "$targetStudent" },
        },
      },
    ]);

    const campaignStats = await MarketingCampaign.aggregate([
      {
        $match: {
          createdAt: dateFilter,
          status: "active",
        },
      },
      {
        $group: {
          _id: null,
          activeCampaigns: { $sum: 1 },
          totalTargets: { $sum: "$stats.totalTargets" },
          totalMessages: { $sum: "$stats.messagesSent" },
        },
      },
    ]);

    const evaluationStats = await StudentEvaluation.aggregate([
      {
        $match: {
          "metadata.evaluatedAt": dateFilter,
        },
      },
      {
        $group: {
          _id: "$finalDecision",
          count: { $sum: 1 },
        },
      },
    ]);

    const decisions = {
      pass: evaluationStats.find((e) => e._id === "pass")?.count || 0,
      review: evaluationStats.find((e) => e._id === "review")?.count || 0,
      repeat: evaluationStats.find((e) => e._id === "repeat")?.count || 0,
    };

    return {
      timeframe,
      total: {
        actions: totalStats[0]?.totalActions || 0,
        completed: totalStats[0]?.totalCompleted || 0,
        students: totalStats[0]?.uniqueStudents?.length || 0,
        successRate: totalStats[0]?.totalActions
          ? parseFloat(((totalStats[0]?.totalCompleted / totalStats[0]?.totalActions) * 100).toFixed(2))
          : 0,
      },
      byActionType: stats.reduce((acc, stat) => {
        acc[stat._id] = {
          total: stat.total,
          completed: stat.completed,
          failed: stat.failed,
          successRate: parseFloat(((stat.completed / stat.total) * 100).toFixed(2)),
        };
        return acc;
      }, {}),
      campaigns: {
        active: campaignStats[0]?.activeCampaigns || 0,
        totalTargets: campaignStats[0]?.totalTargets || 0,
        messagesSent: campaignStats[0]?.totalMessages || 0,
      },
      evaluations: decisions,
    };
  } catch (error) {
    console.error("❌ Error getting marketing stats:", error);
    throw error;
  }
}

/**
 * ✅ فلترة التاريخ
 */
function getDateFilter(timeframe) {
  const now = new Date();
  let startDate;

  switch (timeframe) {
    case "day":
      startDate = new Date(now.setDate(now.getDate() - 1));
      break;
    case "week":
      startDate = new Date(now.setDate(now.getDate() - 7));
      break;
    case "month":
      startDate = new Date(now.setMonth(now.getMonth() - 1));
      break;
    case "quarter":
      startDate = new Date(now.setMonth(now.getMonth() - 3));
      break;
    case "year":
      startDate = new Date(now.setFullYear(now.getFullYear() - 1));
      break;
    default:
      startDate = new Date(now.setMonth(now.getMonth() - 1));
  }

  return { $gte: startDate };
}

export default {
  triggerEvaluationFollowup,
  onGroupCompletedMarketing,
  getMarketingStats,
  executeMarketingAction,
};